### ISSUE TITLE
Any chance of updating this to the 'new' Conky syntax?

### ISSUE THREAD

**Issue by ghost** [oliverseal/Conky.tmLanguage#1]
I mean the syntax, introduced in the last year or so, that, for example:
- uses `true` and `false` instead of `yes` and `no';
- uses `--` for comments within the configuration section.

As things stand, a comment such as 

`-- I changed this yesterday`

has the letters 'yes' highlighted!

**Comment by oliverseal** [comment]
Release 0.2.0 covers the basics. Multiline comments aren't supported yet. Honestly, I don't use Sublime Text anymore except as a glorified notepad. IntelliJ finally got me.
Should get picked up by the package control channel sometime in the next day.

**Comment by ghost** [comment]
> Release 0.2.0 covers the basics. Multiline comments aren't supported yet. 

I'd like to point out that that even in a non-comment line, the text 'no' gets highlighted - as if it were a keyword - in the following:

![image](https://cloud.githubusercontent.com/assets/9998846/23848159/c3f769e0-07cd-11e7-9eb4-541aa42d46c5.png)

I could try myself to hack the plugin to stop it recognising 'yes' and 'no' (which have been replaced in the new Conky by 'true' and 'false') but that is not quite the underlying problem here.

Still, if the package isn't maintained, it is maintained. Thanks for creating it in the first place.

**Comment by ghost** [comment]
It would be nice were someone able and willing to fix the problem.

![image](https://user-images.githubusercontent.com/9998846/50747323-2ed33c80-122b-11e9-8b79-76eabcbfc706.png)
